package org.apache.tika.metadata;

/* loaded from: classes4.dex */
public interface IPTC {
    public static final Property ADDITIONAL_MODEL_INFO;
    public static final Property ARTWORK_OR_OBJECT;
    public static final Property ARTWORK_OR_OBJECT_DETAIL_COPYRIGHT_NOTICE;
    public static final Property ARTWORK_OR_OBJECT_DETAIL_CREATOR;
    public static final Property ARTWORK_OR_OBJECT_DETAIL_DATE_CREATED;
    public static final Property ARTWORK_OR_OBJECT_DETAIL_SOURCE;
    public static final Property ARTWORK_OR_OBJECT_DETAIL_SOURCE_INVENTORY_NUMBER;
    public static final Property ARTWORK_OR_OBJECT_DETAIL_TITLE;

    @Deprecated
    public static final Property CATEGORY;
    public static final Property CITY;
    public static final Property CONTACT_INFO_ADDRESS;
    public static final Property CONTACT_INFO_CITY;
    public static final Property CONTACT_INFO_COUNTRY;
    public static final Property CONTACT_INFO_EMAIL;
    public static final Property CONTACT_INFO_PHONE;
    public static final Property CONTACT_INFO_POSTAL_CODE;
    public static final Property CONTACT_INFO_STATE_PROVINCE;
    public static final Property CONTACT_INFO_WEB_URL;
    public static final Property CONTROLLED_VOCABULARY_TERM;
    public static final Property COPYRIGHT_NOTICE;
    public static final Property COPYRIGHT_OWNER;
    public static final Property COPYRIGHT_OWNER_ID;

    @Deprecated
    public static final String COPYRIGHT_OWNER_ID_WRONG_CASE = "plus:CopyrightOwnerId";
    public static final Property COPYRIGHT_OWNER_NAME;
    public static final Property COUNTRY;
    public static final Property COUNTRY_CODE;
    public static final Property CREATOR;
    public static final Property CREATORS_CONTACT_INFO;
    public static final Property CREATORS_JOB_TITLE;
    public static final Property CREDIT_LINE;
    public static final Property DATE_CREATED;
    public static final Property DESCRIPTION;
    public static final Property DESCRIPTION_WRITER;
    public static final Property DIGITAL_IMAGE_GUID;

    @Deprecated
    public static final Property DIGITAL_SOURCE_FILE_TYPE;
    public static final Property DIGITAL_SOURCE_TYPE;
    public static final Property EVENT;
    public static final Property HEADLINE;
    public static final Property IMAGE_CREATOR;
    public static final Property IMAGE_CREATOR_ID;

    @Deprecated
    public static final String IMAGE_CREATOR_ID_WRONG_CASE = "plus:ImageCreatorId";
    public static final Property IMAGE_CREATOR_NAME;
    public static final Property IMAGE_REGISTRY_ENTRY;
    public static final Property IMAGE_SUPPLIER;
    public static final Property IMAGE_SUPPLIER_ID;

    @Deprecated
    public static final String IMAGE_SUPPLIER_ID_WRONG_CASE = "plus:ImageSupplierId";
    public static final Property IMAGE_SUPPLIER_IMAGE_ID;
    public static final Property IMAGE_SUPPLIER_NAME;
    public static final Property INSTRUCTIONS;
    public static final Property INTELLECTUAL_GENRE;
    public static final Property IPTC_LAST_EDITED;
    public static final Property JOB_ID;
    public static final Property KEYWORDS;
    public static final Property LICENSOR;
    public static final Property LICENSOR_CITY;
    public static final Property LICENSOR_COUNTRY;
    public static final Property LICENSOR_EMAIL;
    public static final Property LICENSOR_EXTENDED_ADDRESS;
    public static final Property LICENSOR_ID;

    @Deprecated
    public static final String LICENSOR_ID_WRONG_CASE = "plus:LicensorId";
    public static final Property LICENSOR_NAME;
    public static final Property LICENSOR_POSTAL_CODE;
    public static final Property LICENSOR_REGION;
    public static final Property LICENSOR_STREET_ADDRESS;
    public static final Property LICENSOR_TELEPHONE_1;
    public static final Property LICENSOR_TELEPHONE_2;
    public static final Property LICENSOR_URL;
    public static final Property LOCATION_CREATED;
    public static final Property LOCATION_CREATED_CITY;
    public static final Property LOCATION_CREATED_COUNTRY_CODE;
    public static final Property LOCATION_CREATED_COUNTRY_NAME;
    public static final Property LOCATION_CREATED_PROVINCE_OR_STATE;
    public static final Property LOCATION_CREATED_SUBLOCATION;
    public static final Property LOCATION_CREATED_WORLD_REGION;
    public static final Property LOCATION_SHOWN;
    public static final Property LOCATION_SHOWN_CITY;
    public static final Property LOCATION_SHOWN_COUNTRY_CODE;
    public static final Property LOCATION_SHOWN_COUNTRY_NAME;
    public static final Property LOCATION_SHOWN_PROVINCE_OR_STATE;
    public static final Property LOCATION_SHOWN_SUBLOCATION;
    public static final Property LOCATION_SHOWN_WORLD_REGION;
    public static final Property MAX_AVAIL_HEIGHT;
    public static final Property MAX_AVAIL_WIDTH;
    public static final Property MINOR_MODEL_AGE_DISCLOSURE;
    public static final Property MODEL_AGE;
    public static final Property MODEL_RELEASE_ID;
    public static final Property MODEL_RELEASE_STATUS;
    public static final String NAMESPACE_URI_IPTC_CORE = "http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/";
    public static final String NAMESPACE_URI_IPTC_EXT = "http://iptc.org/std/Iptc4xmpExt/2008-02-29/";
    public static final String NAMESPACE_URI_PLUS = "http://ns.useplus.org/ldf/xmp/1.0/";
    public static final Property ORGANISATION_CODE;
    public static final Property ORGANISATION_NAME;
    public static final Property PERSON;
    public static final Property PLUS_VERSION;
    public static final String PREFIX_IPTC_CORE = "Iptc4xmpCore";
    public static final String PREFIX_IPTC_EXT = "Iptc4xmpExt";
    public static final String PREFIX_PLUS = "plus";
    public static final Property[] PROPERTY_GROUP_IPTC_CORE;
    public static final Property[] PROPERTY_GROUP_IPTC_EXT;
    public static final Property PROPERTY_RELEASE_ID;
    public static final Property PROPERTY_RELEASE_STATUS;
    public static final Property PROVINCE_OR_STATE;
    public static final Property REGISTRY_ENTRY_CREATED_ITEM_ID;
    public static final Property REGISTRY_ENTRY_CREATED_ORGANISATION_ID;
    public static final Property RIGHTS_USAGE_TERMS;
    public static final Property SCENE_CODE;
    public static final Property SOURCE;
    public static final Property SUBJECT_CODE;
    public static final Property SUBLOCATION;

    @Deprecated
    public static final Property SUPPLEMENTAL_CATEGORIES;
    public static final Property TITLE;

    @Deprecated
    public static final Property URGENCY;

    static {
        Property property = Photoshop.CITY;
        CITY = property;
        Property property2 = Photoshop.COUNTRY;
        COUNTRY = property2;
        Property propertyInternalText = Property.internalText("Iptc4xmpCore:CountryCode");
        COUNTRY_CODE = propertyInternalText;
        Property property3 = DublinCore.DESCRIPTION;
        DESCRIPTION = property3;
        Property property4 = Photoshop.HEADLINE;
        HEADLINE = property4;
        Property propertyInternalText2 = Property.internalText("Iptc4xmpCore:IntellectualGenre");
        INTELLECTUAL_GENRE = propertyInternalText2;
        Property property5 = DublinCore.SUBJECT;
        KEYWORDS = property5;
        Property property6 = Photoshop.STATE;
        PROVINCE_OR_STATE = property6;
        Property propertyInternalTextBag = Property.internalTextBag("Iptc4xmpCore:Scene");
        SCENE_CODE = propertyInternalTextBag;
        Property propertyInternalTextBag2 = Property.internalTextBag("Iptc4xmpCore:SubjectCode");
        SUBJECT_CODE = propertyInternalTextBag2;
        Property propertyInternalText3 = Property.internalText("Iptc4xmpCore:Location");
        SUBLOCATION = propertyInternalText3;
        Property property7 = Photoshop.DATE_CREATED;
        DATE_CREATED = property7;
        Property property8 = Photoshop.CAPTION_WRITER;
        DESCRIPTION_WRITER = property8;
        Property property9 = Photoshop.INSTRUCTIONS;
        INSTRUCTIONS = property9;
        Property property10 = Photoshop.TRANSMISSION_REFERENCE;
        JOB_ID = property10;
        Property property11 = DublinCore.TITLE;
        TITLE = property11;
        Property property12 = DublinCore.RIGHTS;
        COPYRIGHT_NOTICE = property12;
        Property property13 = DublinCore.CREATOR;
        CREATOR = property13;
        CREATORS_CONTACT_INFO = Property.internalText("Iptc4xmpCore:CreatorContactInfo");
        Property property14 = Photoshop.AUTHORS_POSITION;
        CREATORS_JOB_TITLE = property14;
        Property property15 = Photoshop.CREDIT;
        CREDIT_LINE = property15;
        Property property16 = XMPRights.USAGE_TERMS;
        RIGHTS_USAGE_TERMS = property16;
        Property property17 = Photoshop.SOURCE;
        SOURCE = property17;
        Property propertyInternalTextBag3 = Property.internalTextBag("Iptc4xmpCore:CiAdrExtadr");
        CONTACT_INFO_ADDRESS = propertyInternalTextBag3;
        Property propertyInternalText4 = Property.internalText("Iptc4xmpCore:CiAdrCity");
        CONTACT_INFO_CITY = propertyInternalText4;
        Property propertyInternalText5 = Property.internalText("Iptc4xmpCore:CiAdrCtry");
        CONTACT_INFO_COUNTRY = propertyInternalText5;
        Property propertyInternalTextBag4 = Property.internalTextBag("Iptc4xmpCore:CiEmailWork");
        CONTACT_INFO_EMAIL = propertyInternalTextBag4;
        Property propertyInternalTextBag5 = Property.internalTextBag("Iptc4xmpCore:CiTelWork");
        CONTACT_INFO_PHONE = propertyInternalTextBag5;
        Property propertyInternalText6 = Property.internalText("Iptc4xmpCore:CiAdrPcode");
        CONTACT_INFO_POSTAL_CODE = propertyInternalText6;
        Property propertyInternalText7 = Property.internalText("Iptc4xmpCore:CiAdrRegion");
        CONTACT_INFO_STATE_PROVINCE = propertyInternalText7;
        Property propertyInternalTextBag6 = Property.internalTextBag("Iptc4xmpCore:CiUrlWork");
        CONTACT_INFO_WEB_URL = propertyInternalTextBag6;
        URGENCY = Photoshop.URGENCY;
        CATEGORY = Photoshop.CATEGORY;
        SUPPLEMENTAL_CATEGORIES = Photoshop.SUPPLEMENTAL_CATEGORIES;
        Property propertyInternalText8 = Property.internalText("Iptc4xmpExt:AddlModelInfo");
        ADDITIONAL_MODEL_INFO = propertyInternalText8;
        ARTWORK_OR_OBJECT = Property.internalTextBag("Iptc4xmpExt:ArtworkOrObject");
        Property propertyInternalTextBag7 = Property.internalTextBag("Iptc4xmpExt:OrganisationInImageCode");
        ORGANISATION_CODE = propertyInternalTextBag7;
        Property propertyInternalTextBag8 = Property.internalTextBag("Iptc4xmpExt:CVterm");
        CONTROLLED_VOCABULARY_TERM = propertyInternalTextBag8;
        LOCATION_SHOWN = Property.internalTextBag("Iptc4xmpExt:LocationShown");
        Property propertyInternalTextBag9 = Property.internalTextBag("Iptc4xmpExt:ModelAge");
        MODEL_AGE = propertyInternalTextBag9;
        Property propertyInternalTextBag10 = Property.internalTextBag("Iptc4xmpExt:OrganisationInImageName");
        ORGANISATION_NAME = propertyInternalTextBag10;
        Property propertyInternalTextBag11 = Property.internalTextBag("Iptc4xmpExt:PersonInImage");
        PERSON = propertyInternalTextBag11;
        Property propertyInternalText9 = Property.internalText("Iptc4xmpExt:DigImageGUID");
        DIGITAL_IMAGE_GUID = propertyInternalText9;
        DIGITAL_SOURCE_FILE_TYPE = Property.internalText("Iptc4xmpExt:DigitalSourcefileType");
        Property propertyInternalText10 = Property.internalText("Iptc4xmpExt:DigitalSourceType");
        DIGITAL_SOURCE_TYPE = propertyInternalText10;
        Property propertyInternalText11 = Property.internalText("Iptc4xmpExt:Event");
        EVENT = propertyInternalText11;
        IMAGE_REGISTRY_ENTRY = Property.internalTextBag("Iptc4xmpExt:RegistryId");
        IMAGE_SUPPLIER = Property.internalText("plus:ImageSupplier");
        Property propertyComposite = Property.composite(Property.internalText("plus:ImageSupplierID"), new Property[]{Property.internalText(IMAGE_SUPPLIER_ID_WRONG_CASE)});
        IMAGE_SUPPLIER_ID = propertyComposite;
        Property propertyInternalText12 = Property.internalText("plus:ImageSupplierName");
        IMAGE_SUPPLIER_NAME = propertyInternalText12;
        Property propertyInternalText13 = Property.internalText("plus:ImageSupplierImageID");
        IMAGE_SUPPLIER_IMAGE_ID = propertyInternalText13;
        Property propertyInternalDate = Property.internalDate("Iptc4xmpExt:IptcLastEdited");
        IPTC_LAST_EDITED = propertyInternalDate;
        LOCATION_CREATED = Property.internalTextBag("Iptc4xmpExt:LocationCreated");
        Property propertyInternalInteger = Property.internalInteger("Iptc4xmpExt:MaxAvailHeight");
        MAX_AVAIL_HEIGHT = propertyInternalInteger;
        Property propertyInternalInteger2 = Property.internalInteger("Iptc4xmpExt:MaxAvailWidth");
        MAX_AVAIL_WIDTH = propertyInternalInteger2;
        Property propertyInternalText14 = Property.internalText("plus:Version");
        PLUS_VERSION = propertyInternalText14;
        COPYRIGHT_OWNER = Property.internalTextBag("plus:CopyrightOwner");
        Property propertyComposite2 = Property.composite(Property.internalTextBag("plus:CopyrightOwnerID"), new Property[]{Property.internalTextBag(COPYRIGHT_OWNER_ID_WRONG_CASE)});
        COPYRIGHT_OWNER_ID = propertyComposite2;
        Property propertyInternalTextBag12 = Property.internalTextBag("plus:CopyrightOwnerName");
        COPYRIGHT_OWNER_NAME = propertyInternalTextBag12;
        IMAGE_CREATOR = Property.internalTextBag("plus:ImageCreator");
        Property propertyComposite3 = Property.composite(Property.internalTextBag("plus:ImageCreatorID"), new Property[]{Property.internalTextBag(IMAGE_CREATOR_ID_WRONG_CASE)});
        IMAGE_CREATOR_ID = propertyComposite3;
        Property propertyInternalTextBag13 = Property.internalTextBag("plus:ImageCreatorName");
        IMAGE_CREATOR_NAME = propertyInternalTextBag13;
        LICENSOR = Property.internalTextBag("plus:Licensor");
        Property propertyComposite4 = Property.composite(Property.internalTextBag("plus:LicensorID"), new Property[]{Property.internalTextBag(LICENSOR_ID_WRONG_CASE)});
        LICENSOR_ID = propertyComposite4;
        Property propertyInternalTextBag14 = Property.internalTextBag("plus:LicensorName");
        LICENSOR_NAME = propertyInternalTextBag14;
        Property propertyInternalTextBag15 = Property.internalTextBag("plus:LicensorCity");
        LICENSOR_CITY = propertyInternalTextBag15;
        Property propertyInternalTextBag16 = Property.internalTextBag("plus:LicensorCountry");
        LICENSOR_COUNTRY = propertyInternalTextBag16;
        Property propertyInternalTextBag17 = Property.internalTextBag("plus:LicensorEmail");
        LICENSOR_EMAIL = propertyInternalTextBag17;
        Property propertyInternalTextBag18 = Property.internalTextBag("plus:LicensorExtendedAddress");
        LICENSOR_EXTENDED_ADDRESS = propertyInternalTextBag18;
        Property propertyInternalTextBag19 = Property.internalTextBag("plus:LicensorPostalCode");
        LICENSOR_POSTAL_CODE = propertyInternalTextBag19;
        Property propertyInternalTextBag20 = Property.internalTextBag("plus:LicensorRegion");
        LICENSOR_REGION = propertyInternalTextBag20;
        Property propertyInternalTextBag21 = Property.internalTextBag("plus:LicensorStreetAddress");
        LICENSOR_STREET_ADDRESS = propertyInternalTextBag21;
        Property propertyInternalTextBag22 = Property.internalTextBag("plus:LicensorTelephone1");
        LICENSOR_TELEPHONE_1 = propertyInternalTextBag22;
        Property propertyInternalTextBag23 = Property.internalTextBag("plus:LicensorTelephone2");
        LICENSOR_TELEPHONE_2 = propertyInternalTextBag23;
        Property propertyInternalTextBag24 = Property.internalTextBag("plus:LicensorURL");
        LICENSOR_URL = propertyInternalTextBag24;
        Property propertyInternalText15 = Property.internalText("plus:MinorModelAgeDisclosure");
        MINOR_MODEL_AGE_DISCLOSURE = propertyInternalText15;
        Property propertyInternalTextBag25 = Property.internalTextBag("plus:ModelReleaseID");
        MODEL_RELEASE_ID = propertyInternalTextBag25;
        Property propertyInternalText16 = Property.internalText("plus:ModelReleaseStatus");
        MODEL_RELEASE_STATUS = propertyInternalText16;
        Property propertyInternalTextBag26 = Property.internalTextBag("plus:PropertyReleaseID");
        PROPERTY_RELEASE_ID = propertyInternalTextBag26;
        Property propertyInternalText17 = Property.internalText("plus:PropertyReleaseStatus");
        PROPERTY_RELEASE_STATUS = propertyInternalText17;
        Property propertyInternalTextBag27 = Property.internalTextBag("Iptc4xmpExt:AOCopyrightNotice");
        ARTWORK_OR_OBJECT_DETAIL_COPYRIGHT_NOTICE = propertyInternalTextBag27;
        Property propertyInternalTextBag28 = Property.internalTextBag("Iptc4xmpExt:AOCreator");
        ARTWORK_OR_OBJECT_DETAIL_CREATOR = propertyInternalTextBag28;
        Property propertyInternalTextBag29 = Property.internalTextBag("Iptc4xmpExt:AODateCreated");
        ARTWORK_OR_OBJECT_DETAIL_DATE_CREATED = propertyInternalTextBag29;
        Property propertyInternalTextBag30 = Property.internalTextBag("Iptc4xmpExt:AOSource");
        ARTWORK_OR_OBJECT_DETAIL_SOURCE = propertyInternalTextBag30;
        Property propertyInternalTextBag31 = Property.internalTextBag("Iptc4xmpExt:AOSourceInvNo");
        ARTWORK_OR_OBJECT_DETAIL_SOURCE_INVENTORY_NUMBER = propertyInternalTextBag31;
        Property propertyInternalTextBag32 = Property.internalTextBag("Iptc4xmpExt:AOTitle");
        ARTWORK_OR_OBJECT_DETAIL_TITLE = propertyInternalTextBag32;
        Property propertyInternalTextBag33 = Property.internalTextBag("Iptc4xmpExt:LocationShownCity");
        LOCATION_SHOWN_CITY = propertyInternalTextBag33;
        Property propertyInternalTextBag34 = Property.internalTextBag("Iptc4xmpExt:LocationShownCountryCode");
        LOCATION_SHOWN_COUNTRY_CODE = propertyInternalTextBag34;
        Property propertyInternalTextBag35 = Property.internalTextBag("Iptc4xmpExt:LocationShownCountryName");
        LOCATION_SHOWN_COUNTRY_NAME = propertyInternalTextBag35;
        Property propertyInternalTextBag36 = Property.internalTextBag("Iptc4xmpExt:LocationShownProvinceState");
        LOCATION_SHOWN_PROVINCE_OR_STATE = propertyInternalTextBag36;
        Property propertyInternalTextBag37 = Property.internalTextBag("Iptc4xmpExt:LocationShownSublocation");
        LOCATION_SHOWN_SUBLOCATION = propertyInternalTextBag37;
        Property propertyInternalTextBag38 = Property.internalTextBag("Iptc4xmpExt:LocationShownWorldRegion");
        LOCATION_SHOWN_WORLD_REGION = propertyInternalTextBag38;
        Property propertyInternalText18 = Property.internalText("Iptc4xmpExt:LocationCreatedCity");
        LOCATION_CREATED_CITY = propertyInternalText18;
        Property propertyInternalText19 = Property.internalText("Iptc4xmpExt:LocationCreatedCountryCode");
        LOCATION_CREATED_COUNTRY_CODE = propertyInternalText19;
        Property propertyInternalText20 = Property.internalText("Iptc4xmpExt:LocationCreatedCountryName");
        LOCATION_CREATED_COUNTRY_NAME = propertyInternalText20;
        Property propertyInternalText21 = Property.internalText("Iptc4xmpExt:LocationCreatedProvinceState");
        LOCATION_CREATED_PROVINCE_OR_STATE = propertyInternalText21;
        Property propertyInternalText22 = Property.internalText("Iptc4xmpExt:LocationCreatedSublocation");
        LOCATION_CREATED_SUBLOCATION = propertyInternalText22;
        Property propertyInternalText23 = Property.internalText("Iptc4xmpExt:LocationCreatedWorldRegion");
        LOCATION_CREATED_WORLD_REGION = propertyInternalText23;
        Property propertyInternalTextBag39 = Property.internalTextBag("Iptc4xmpExt:RegItemId");
        REGISTRY_ENTRY_CREATED_ITEM_ID = propertyInternalTextBag39;
        Property propertyInternalTextBag40 = Property.internalTextBag("Iptc4xmpExt:RegOrgId");
        REGISTRY_ENTRY_CREATED_ORGANISATION_ID = propertyInternalTextBag40;
        PROPERTY_GROUP_IPTC_CORE = new Property[]{property, property2, propertyInternalText, property3, property4, propertyInternalText2, property5, property6, propertyInternalTextBag, propertyInternalTextBag2, propertyInternalText3, property7, property8, property9, property10, property11, property12, property13, property14, property15, property16, property17, propertyInternalTextBag3, propertyInternalText4, propertyInternalText5, propertyInternalTextBag4, propertyInternalTextBag5, propertyInternalText6, propertyInternalText7, propertyInternalTextBag6};
        PROPERTY_GROUP_IPTC_EXT = new Property[]{propertyInternalText8, propertyInternalTextBag7, propertyInternalTextBag8, propertyInternalTextBag9, propertyInternalTextBag10, propertyInternalTextBag11, propertyInternalText9, propertyInternalText10, propertyInternalText11, propertyComposite, propertyInternalText12, propertyInternalText13, propertyInternalDate, propertyInternalInteger, propertyInternalInteger2, propertyInternalText14, propertyComposite2, propertyInternalTextBag12, propertyComposite3, propertyInternalTextBag13, propertyComposite4, propertyInternalTextBag14, propertyInternalTextBag15, propertyInternalTextBag16, propertyInternalTextBag17, propertyInternalTextBag18, propertyInternalTextBag19, propertyInternalTextBag20, propertyInternalTextBag21, propertyInternalTextBag22, propertyInternalTextBag23, propertyInternalTextBag24, propertyInternalText15, propertyInternalTextBag25, propertyInternalText16, propertyInternalTextBag26, propertyInternalText17, propertyInternalTextBag27, propertyInternalTextBag28, propertyInternalTextBag29, propertyInternalTextBag30, propertyInternalTextBag31, propertyInternalTextBag32, propertyInternalTextBag33, propertyInternalTextBag34, propertyInternalTextBag35, propertyInternalTextBag36, propertyInternalTextBag37, propertyInternalTextBag38, propertyInternalText18, propertyInternalText19, propertyInternalText20, propertyInternalText21, propertyInternalText22, propertyInternalText23, propertyInternalTextBag39, propertyInternalTextBag40};
    }
}
